apiVersion: v2
name: placeos-metrics
description: A chart to deploy cluster metrics, monitoring and alerting

type: application
version: 0.1.0

dependencies:
  - name: kube-prometheus
    version: ~8.9.1
    repository: https://charts.bitnami.com/bitnami
    condition: kube-prometheus.enabled

  - name: grafana
    version: ~8.2.33
    repository: https://charts.bitnami.com/bitnami
    condition: grafana.enabled

  - name: grafana-loki
    version: ~2.7.1
    repository: https://charts.bitnami.com/bitnami
    condition: grafana-loki.enabled

  - name: grafana-tempo
    version: ~2.2.1
    repository: https://charts.bitnami.com/bitnami
    condition: grafana-tempo.enabled