## Metrics

# Prometheus collects node & k8s metrics
# https://github.com/bitnami/charts/tree/main/bitnami/kube-prometheus
kube-prometheus:
  enabled: true
  prometheus:
    persistence:
      size: 100M

# Grafana provides dashboards and logging via providers (prometheus, loki, tempo, influx)
# https://github.com/bitnami/charts/tree/main/bitnami/grafana
grafana:
  enabled: true
  persistence:
    size: 100M
  ingress:
    enabled: true
    hostname: metrics.local
    annotations: {}
    ingressClassName: nginx
    tls: true
    selfSigned: true
  admin:
    user: place-admin
    password: "" # leave blank for random
  datasources:
    secretName: placeos-grafana-datasources

# Loki collects pod logs
# https://github.com/bitnami/charts/tree/main/bitnami/grafana-loki
grafana-loki:
  enabled: true
  compactor:
    persistence:
      enabled: false
      size: 100M
  ingester:
    persistence:
      enabled: true
      size: 100M
  querier:
    persistence:
      enabled: false
      size: 100M

# Tempo ingests tracing from PlaceOS services
# https://github.com/bitnami/charts/tree/main/bitnami/grafana-tempo
grafana-tempo:
  enabled: true
  ingester:
    persistence:
      enabled: true
      size: 100M
