grafana:
  ingress:
    hostname: metrics.local
    path: /analytics
  grafana:
    extraEnvVars:
      - name: GF_SERVER_ROOT_URL
        value: "https://metrics.local/analytics"
      - name: GF_SERVER_SERVE_FROM_SUB_PATH
        value: "true"
