grafana:
  ingress:
    hostname: metrics.local
    path: /analytics
    pathType: Prefix
    ingressClassName: nginx
    selfSigned: true
    #annotations:
    #  cert-manager.io/cluster-issuer: letsencrypt-prod
  grafana:
    extraEnvVars:
      - name: GF_SERVER_ROOT_URL
        value: "https://metrics.local/analytics"
      - name: GF_SERVER_SERVE_FROM_SUB_PATH
        value: "true"
