## Metrics

# Prometheus collects node & k8s metrics
# https://github.com/bitnami/charts/tree/main/bitnami/kube-prometheus
kube-prometheus:
  enabled: true
  operator:
    # This creates a Service in the kube-system namespace which exposes a set of prometheus data to grafana with a `service` label 
    # If you have incorrect (2x, 3x, etc) values in grafana dashboards you likely have orphaned Services from previous deployments
    kubeletService:
      enabled: true 
  prometheus:
    persistence:
      size: 1Gi

# Grafana provides dashboards and logging via providers (prometheus, loki, tempo, influx)
# https://github.com/bitnami/charts/tree/main/bitnami/grafana
grafana:
  enabled: true
  persistence:
    size: 100Mi
  ingress:
    enabled: true
    hostname: metrics.local
    annotations: {}
    ingressClassName: nginx
    tls: true
    selfSigned: true
  admin:
    user: place-admin
    password: "" # leave blank for random
  datasources:
    secretName: placeos-grafana-datasources
  dashboardsProvider:
    enabled: true
    configMapName: placeos-grafana-dashboard-provider
  dashboardsConfigMaps:
    - configMapName: placeos-grafana-dashboards-postgres
      fileName: postgres.json
      folderName: Database
    - configMapName: placeos-grafana-dashboards-elasticsearch
      fileName: elasticsearch.json
      folderName: Database
    - configMapName: placeos-grafana-dashboards-alertmanager
      fileName: alertmanager.json
      folderName: Alerts
    - configMapName: placeos-grafana-dashboards-api-server
      fileName: api-server.json
      folderName: Kubernetes
    - configMapName: placeos-grafana-dashboards-cluster-monitoring
      fileName: cluster-monitoring.json
      folderName: Kubernetes
    - configMapName: placeos-grafana-dashboards-node-exporter
      fileName: node-exporter.json
      folderName: Kubernetes
    - configMapName: placeos-grafana-dashboards-volumes
      fileName: volumes.json
      folderName: Kubernetes
    - configMapName: placeos-grafana-dashboards-placeos-logs
      fileName: placeos-logs.json
      folderName: PlaceOS
    - configMapName: placeos-grafana-dashboards-pod-metrics
      fileName: pod-metrics.json
      folderName: PlaceOS

# Loki collects pod logs
# https://github.com/bitnami/charts/tree/main/bitnami/grafana-loki
grafana-loki:
  enabled: true
  compactor:
    persistence:
      enabled: true
      size: 100Mi
  ingester:
    persistence:
      enabled: true
      size: 1Gi
  querier:
    persistence:
      enabled: false
      size: 100Mi

# Tempo ingests tracing from PlaceOS services
# https://github.com/bitnami/charts/tree/main/bitnami/grafana-tempo
grafana-tempo:
  enabled: true
  ingester:
    persistence:
      enabled: true
      size: 1Gi
