## Metrics
kube-prometheus:
  enabled: true
  prometheus:
    persistence:
      size: 100M

grafana:
  enabled: true
  persistence:
    size: 100M
  ingress:
    enabled: true
    hostname: metrics.local
    annotations: {}
    ingressClassName: nginx
    tls: true
    selfSigned: true
  admin:
    user: place-admin
    password: "" # leave blank for random

grafana-loki:
  enabled: true
  compactor:
    persistence:
      enabled: false
      size: 100M
  ingester:
    persistence:
      enabled: false
      size: 100M
  querier:
    persistence:
      enabled: false
      size: 100M

grafana-tempo:
  enabled: true
  ingester:
    persistence:
      size: 100M
