kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gcp-regionalpv
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: regional-pd
volumeBindingMode: WaitForFirstConsumer