# -- Default values for frontends.
# -- This is a YAML-formatted file.
# -- Declare variables to be passed into your templates.

# -- httpSidecar if true include http server side car container to frontend pod to serve static UI resources.
httpSidecar: false

# -- httpDeployment if httpSidecar=false use a seperate Deployment to serve static html using the variables in httpDeployment. Also see persistentVolume.accessModes
httpDeployment:
  replicaCount: 1
  podPriorityClassName: medium
  image:
    repository: nginx
    tag: "1.18"
    pullPolicy: IfNotPresent
    # -- tag Overrides the image tag whose default is the chart appVersion.
    # tag:

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  podAnnotations: {}

  # -- podSecurityContext for the pod
  podSecurityContext:
    # -- fsGroup is defined at container build time for the frontend container and in most circumstances should not be changed
    fsGroup: 10001

  # -- securityContext for the container
  securityContext:
    allowPrivilegeEscalation: true
    capabilities:
      add:
      - NET_BIND_SERVICE
      drop:
      - ALL
    readOnlyRootFilesystem: false
    # -- runAsUser is defined at container build time for the frontend container and in most circumstances should not be changed
    runAsUser: 10001

  resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}


# -- autoscaling configuration for http deployment if httpSidecar=false
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# -- deployment configuration for the frontend container
deployment:
  replicaCount: 1
  podPriorityClassName: medium
  image:
    repository: placeos/frontends
    pullPolicy: IfNotPresent
    # -- tag Overrides the image tag whose default is the chart appVersion.
    # tag:

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  podAnnotations: {}

  # -- podSecurityContext for the pod
  podSecurityContext:
    # -- fsGroup is defined at container build time and in most circumstances should not be changed
    fsGroup: 10001

  # -- securityContext for the container
  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    # -- runAsUser is defined at container build time and in most circumstances should not be changed
    runAsUser: 10001
  resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

serviceAccount:
  # -- Specifies whether a service account should be created
  create: false
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- service exposed by frontend deployment
service:
  type: ClusterIP
  port: 3000

# -- persistentVolume configuration for the volume that conatains the static resources to serve backend
# persistentVolume.accssMode ReadWriteMany is required for distributed http serving which is set when httpSidecar: true
# see https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
persistentVolume:
  name: www
  accessModes:
    - ReadWriteOnce
  storage: 100Mi

# -- ingress to expose the http server pod services
ingress:
  enabled: true
  annotations: {}
  hosts:
     - host: "_"
       paths:
       - /
  tls:
    - hosts:
        - "_"
# -- service exposed by http server
httpservice:
  type: ClusterIP
  port: 8080

# -- configmap for the deployment exposed as environment variables to the pod
configmap:
  ENV: null
  PLACE_LOADER_WWW: www
  RETHINKDB_DB: null
  RETHINKDB_HOST: null
  RETHINKDB_PORT: 0
  RETHINKDB_USER: null
  SG_ENV: null
  TZ: Australia/Sydney

# -- secrets for the deployment exposed as environment variables to the pod
secrets:
  RETHINKDB_PASSWORD: null
