---
# tasks file for placeos.helm
- name: run block tasks conditionally
  block:
  - name: Get the ingress service endpoint for the place domain
    set_fact:
      ingress: "{{ lookup('community.kubernetes.k8s',
        kind='Service',
        namespace=ingress_namespace,
        resource_name=ingress_service_name ) }}"
    until:
        - ingress.status is defined
        - ingress.status.loadBalancer.ingress[0].ip is defined
    # 5 minutes
    retries: 30
    delay: 10

  - name: extract the ip
    set_fact:
      placeDomain: "{{ ingress.status.loadBalancer.ingress[0].ip }}.xip.io"
  when:
    - chart_state == 'present'
    - placeDomain is undefined

- name: load the PlaceOS Profile vars
  set_fact:
    placeos_profile: "{{ placeos | from_yaml }}"

- name: dump placeos vars
  debug:
    var: placeos_profile
    verbosity: 1

- name: install placeos charts from local filesystem
  community.kubernetes.helm:
    release_name: "{{ chart_release_name }}"
    chart_ref: "{{ placeos_chart_ref }}"
    release_namespace: "{{ release_namespace }}"
    create_namespace: "{{ create_namespace | default( true, true) }}"
    release_values:
      "{{ placeos_profile | default( omit ) }}"
    state: "{{ chart_state | default( 'present', true ) }}"
  when: placeos_profile.enabled | bool
