apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: grafana-to-influx
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: influxdb
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: placeos-metrics
      podSelector:
        matchLabels:
          app.kubernetes.io/name: grafana