apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-placeos-access
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    -  namespaceSelector:
        matchLabels:
          networking/namespace: {{ placeos_namespace }}