# xrethinkdbPassword the admin password for RethinkDb.
#  Used to set the admin password in RethinkDB if enabled then passed to multiple containers in a k8s secret
xrethinkdbPassword: &rethinkdbPassword "{{ rethinkdbPassword }}"

# xsmtpPassword. the smtp password used by triggers
xsmtpPassword: &smtpPassword "{{ smtpPassword | default( '', true ) }}"

# xplacePassword. The value used by the init subchart to set the default domain users password
xplacePassword: &placePassword "{{ placePassword | default( '', true ) }}"

# xserverSecret for the dispatch service
xserverSecret: &serverSecret "{{ serverSecret | default( '', true ) }}"

# xelasticClientEnv configmap values for ElasticSearch Service exposed as environment variables to PlaceOS containers
xelasticClientEnv: &elasticClientEnv
  ES_HOST: "{{ chart_release_name }}-elasticsearch-master.{{ elasticsearch_namespace }}"
  ES_PORT: 9200

# xetcdClientEnv configmap values for Etcd end point Service as environment variables to PlaceOS containers
xetcdClientEnv: &etcdClientEnv
  ETCD_HOST: "etcd-headless.{{ etcd_namespace }}"
  ETCD_PORT: 2379

# xredisClientEnv configmap values for the redis Service exposed as environment variables to PlaceOS containers
xredisClientEnv: &redisClientEnv
  REDIS_URL: "redis://redis-headless.{{ redis_namespace }}:6379"

# xrethinkdbClientEnv configmap values for RethinkDB Service exposed as environment variables to PlaceOS containers
xrethinkdbClientEnv: &rethinkdbClientEnv
  RETHINKDB_HOST: "{{ chart_release_name }}-rethinkdb-proxy.{{ rethinkdb_namespace }}"
  RETHINKDB_PORT: 28015
  RETHINKDB_DB: place_development
  RETHINKDB_USER: admin

xrethinkdbClientSecrets: &rethinkdbClientSecrets
  RETHINKDB_PASSWORD: *rethinkdbPassword

# xsmtpClientSecrets secrets values exposed as environment variables for the trigger service
xsmtpClientSecrets: &smtpClientSecrets
  SMTP_PASS: *smtpPassword

# dispatchSecrets secret values exposed as environment variables for the dispatch service
xdispatchSecrets: &dispatchSecrets
  SERVER_SECRET: *serverSecret

# api is the overide configuration for the embedded api subchart
placeos:
  api:
    enabled: true
    configmap:
      # Service Hosts
      << : *elasticClientEnv
      << : *etcdClientEnv
      << : *redisClientEnv
      << : *rethinkdbClientEnv
    secrets:
      << : *rethinkdbClientSecrets
  # auth is the overide configuration for the embedded auth subchart
  auth:
    enabled: true
    configmap:
      << : *rethinkdbClientEnv
    secrets:
      << : *rethinkdbClientSecrets
  # core is the overide configuration for the embedded core subchart
  core:
    enabled: true
    fullnameOverride: core
    configmap:
      # Service Hosts
      << : *etcdClientEnv
      << : *redisClientEnv
      << : *rethinkdbClientEnv
    secrets:
      << : *rethinkdbClientSecrets
  # dispatch is the overide configuration for the embedded dispatch subchart
  dispatch:
    enabled: true
    fullnameOverride: dispatch
    secrets:
      << : *dispatchSecrets
  # frontends is the overide configuration for the embedded frontends subchart
  frontends:
    enabled: true
    httpSidecar: true
    fullnameOverride: frontends
    configmap:
      PLACE_LOADER_WWW: www
      << : *rethinkdbClientEnv
    secrets:
      << : *rethinkdbClientSecrets
  # rubbersoul is the overide configuration for the embedded rubber-soul subchart
  rubbersoul:
    enabled: true
    fullnameOverride: rubbersoul
    configmap:
      # Service Hosts
      << : *rethinkdbClientEnv
      << : *elasticClientEnv
    secrets:
      << : *rethinkdbClientSecrets
  # triggers is the overide configuration for the embedded triggers subchart
  triggers:
    enabled: true
    fullnameOverride: triggers
    configmap:
      # Service Hosts
      << : *etcdClientEnv
      << : *redisClientEnv
      << : *rethinkdbClientEnv
    secrets:
      << : *rethinkdbClientSecrets
      << : *smtpClientSecrets
  # init is the overide configuration for the embedded init subchart
  init:
    enabled: true
    fullnameOverride: init
    config:
      # Service Hosts
      << : *rethinkdbClientEnv
      << : *elasticClientEnv
      << : *rethinkdbClientSecrets
    secrets:
      PLACE_PASSWORD: *placePassword
  global:
    placeDomain: "localhost"
    customRedirectPort: 8443
  # placeDomain: "{{ placeDomain }}"
  # customRedirectPort: {{ customRedirectPort | default( omit ) }}

###########################################
##### Third Party Supporting Services #####
###########################################

etcd:
  enabled: true
  auth:
    rbac:
      enabled: false
elasticsearch:
  enabled: true
  master:
    replicas: 1
  data:
    replicas: 1
  coordinating:
    replicas: 0
rethinkdb:
  enabled: true
  cluster:
    replicas: 1
  rethinkdbPassword: "{{ rethinkdbPassword }}"
redis:
  enabled: true
  usePassword: false
  cluster:
    enabled: false
influxdb:
  enabled: false
mosquitto:
  enabled: false