---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: False
    ansible_connection_options:
      ansible_connection: local
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: "placeos.helm"
provisioner:
  name: ansible
  log: True
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: "/usr/bin/python3"
  options:
    vvv: True
  lint:
    name: ansible-lint
verifier:
  name: ansible
  lint:
    name: ansible-lint
## If using testinfra
#verifier:
#  name: testinfra
#  options:
#    v: 1
scenario:
  name: ec2
  test_sequence:
    - lint
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy