etcd:
  enabled: true
  fullnameOverride: etcd
  auth:
    rbac:
      enabled: false
elasticsearch:
  enabled: true
  master:
    replicas: 1
  data:
    replicas: 1
  coordinating:
    replicas: 0
rethinkdb:
  enabled: true
  cluster:
    replicas: 1
  rethinkdbPassword: "{{ rethinkdbPassword }}"
redis:
  enabled: true
  fullnameOverride: redis
  usePassword: false
  cluster:
    enabled: false
  configmap: |-
    notify-keyspace-events Kg$
influxdb:
  enabled: false
  fullnameOverride: influxdb
mosquitto:
  enabled: false
  fullnameOverride: mosquitto