{
 "title": "PlaceOS Logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "API",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"api\", namespace=\"placeos\"} |= ``"
    }
   ]
  },
  {
   "title": "Auth",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"auth\", namespace=\"placeos\"} |= ``"
    }
   ]
  },
  {
   "title": "Core",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"core\", namespace=\"placeos\"} |= ``"
    }
   ]
  },
  {
   "title": "Frontend Loader",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{namespace=\"placeos\", app=\"frontendloader\"} |= ``"
    }
   ]
  },
  {
   "title": "Triggers",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{namespace=\"placeos\", app=\"triggers\"} |= ``"
    }
   ]
  },
  {
   "title": "Staff",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{app=\"staff\", namespace=\"placeos\"} |= ``"
    }
   ]
  },
  {
   "title": "Search Ingest",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{app=\"searchingest\", namespace=\"placeos\"} |= ``"
    }
   ]
  },
  {
   "title": "Source",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "{app=\"source\", namespace=\"placeos\"} |= ``"
    }
   ]
  }
 ]
}