apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasource
type: Opaque
stringData:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-operated:9090
      - name: loki
        type: loki
        access: proxy
        url: http://metrics-grafana-loki-gateway:80
      - name: tempo
        type: tempo
        access: proxy
        url: http://metrics-grafana-tempo-querier:3200
