# -- Default values for frontends.
# -- This is a YAML-formatted file.
# -- Declare variables to be passed into your templates.

# -- deployment configuration for the core pod
deployment:
  replicaCount: 1

  podPriorityClassName: high

  image:
    repository: placeos/core
    pullPolicy: IfNotPresent
    # -- tag Overrides the image tag whose default is the chart appVersion.
    # tag:

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  terminationGracePeriodSeconds: 120

  # -- podSecurityContext for the pod
  podSecurityContext:
    # -- fsGroup is defined at container build time and in most circumstances should not be changed
    fsGroup: 10001

  # -- securityContext for the container
  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    # -- runAsUser is defined at container build time and in most circumstances should not be changed
    runAsUser: 10001

  resources:
    limits:
      cpu: 1500m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1280Mi

  nodeSelector: {}

  tolerations: []

  # -- Affinities to ensure multiple pods to not converge to a single node
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: core
              operator: In
              values:
              - core
          topologyKey: kubernetes.io/hostname

serviceAccount:
  # -- Specifies whether a service account should be created
  create: false
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- service exposed by deployment
service:
  type: ClusterIP
  port: 8080

# -- configmap for the deployment exposed as environment variables to the pod
configmap:
  ENV: null
  ETCD_HOST: null
  ETCD_PORT: 0
  REDIS_URL: null
  RETHINKDB_DB: null
  RETHINKDB_HOST: null
  RETHINKDB_PORT: 0
  RETHINKDB_USER: null
  SG_ENV: null
  TZ: Australia/Sydney

# -- secrets for the deployment exposed as environment variables to the pod
secrets:
  RETHINKDB_PASSWORD: null

persistentVolumeClaim:
  accessModes:
    - ReadWriteOnce
  storage: 1Gi

persistentVolumeClaimRepos:
  accessModes:
    - ReadWriteOnce
  storage: 1Gi
