apiVersion: batch/v1
kind: CronJob
metadata:
  name: placeos-restore
  namespace: placeos
spec:
  schedule: 0 0 1 1 *
  concurrencyPolicy: Forbid
  suspend: true
  jobTemplate:
    spec:
      completions: 1
      backoffLimit: 0
      template:
        metadata:
          name: placeos-restore
        spec:
          containers:
            - name: init
              image: placeos/init:placeos-2.2602.5
              command:
                - bash
                - '-c'
              args:
                - >
                  /app/bin/task restore:az host=$PG_HOST user=$PG_USER
                  password=$PG_PASSWORD db=$PG_DB
              envFrom:
                - secretRef:
                    name: postgres-client
                - configMapRef:
                    name: postgres-client
              env:
                - name: PLACE_SKIP_PLACEHOLDERS
                  value: 'true'
                - name: PLACE_DOMAIN
                - name: PLACE_EMAIL
                  value: support@place.tech
                - name: PLACE_AUTH_HOST
                  value: auth:3000
                - name: PLACE_TLS
                  value: 'true'
                - name: AZURE_STORAGE_ACCOUNT_NAME
                  value: <storage-account-name>
                - name: AZURE_STORAGE_ACCOUNT_KEY
                  value: <storage-account-key>
                - name: AZURE_STORAGE_CONTAINER
                  value: <storage-container-name>
                - name: AZURE_STORAGE_BLOB_OBJECT
                  value: <postgres-dump-filename>
                - name: PG_FORCE_RESTORE
                  value: 'true'
              resources: {}
              imagePullPolicy: IfNotPresent
          restartPolicy: Never
      ttlSecondsAfterFinished: 3600
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
