apiVersion: batch/v1
kind: CronJob
metadata:
  name: placeos-secret-rotate
  namespace: placeos
spec:
  schedule: 0 0 1 1 *
  suspend: true
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      completions: 1
      backoffLimit: 0
      template:
        metadata:
          name: placeos-secret-rotate
          creationTimestamp: null
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
          containers:
            - name: init
              image: placeos/init:placeos-2.2409.0
              command:
                - bash
                - '-c'
              args:
                - >
                  /app/bin/task secret:rotate_server_secret host=$PG_HOST user=$PG_USER
                  password=$PG_PASSWORD db=$PG_DB old_secret=$OLD_PLACE_SERVER_SECRET
              envFrom:
                - secretRef:
                    name: postgres-client
                - configMapRef:
                    name: postgres-client
                - secretRef:
                    name: placeos
              env:
                - name: PLACE_SKIP_PLACEHOLDERS
                  value: 'true'
                - name: PLACE_DOMAIN
                - name: PLACE_EMAIL
                  value: support@place.tech
                - name: PLACE_AUTH_HOST
                  value: auth:3000
                - name: PLACE_TLS
                  value: 'true'
              imagePullPolicy: IfNotPresent
          restartPolicy: Never
      ttlSecondsAfterFinished: 3600
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
