apiVersion: batch/v1
kind: CronJob
metadata:
  name: placeos-migrations
  namespace: placeos
spec:
  # Run this Job with `kubectl create job -n placeos --from cronjob/placeos-migrations placeos-migrations` 
  schedule: "0 0 1 1 *" # Suspended so it never runs on line below
  suspend: true
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      completions: 1
      backoffLimit: 0
      ttlSecondsAfterFinished: 3600
      template:
        metadata:
          name: placeos-migrations
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
          containers:
          - name: init
            image: placeos/init:placeos-2.2511.1
            securityContext:
              allowPrivilegeEscalation: false
            command: ["bash", "-c"]
            args:
            - |
              /app/bin/task db:init host=$PG_HOST user=$PG_USER password=$PG_PASSWORD db=$PG_DB
            imagePullPolicy: IfNotPresent
            env:
              - name: PLACE_SKIP_PLACEHOLDERS
                value: "true"
              - name: PLACE_DOMAIN
                value: ""
              - name: PLACE_EMAIL
                value: "support@place.tech"
              - name: PLACE_AUTH_HOST
                value: "auth:3000"
              - name: PLACE_TLS
                value: "true"
            envFrom:
            - secretRef:
                name: postgres-client
            - configMapRef:
                name: postgres-client
          restartPolicy: Never