apiVersion: v1
kind: ServiceAccount
metadata:
  name: place-ops
  namespace: placeos
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: place-ops
  namespace: placeos
rules:
- apiGroups: ["apps", "batch"]
  resources: ["deployments", "deployments/scale", "statefulsets", "statefulsets/scale", "cronjobs"]
  verbs: ["get", "list", "patch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "list", "get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: place-ops
  namespace: placeos
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: place-ops
subjects:
- kind: ServiceAccount
  namespace: placeos
  name: place-ops