
apiVersion: batch/v1
kind: Job
metadata:
  name: add-domain
  namespace: placeos
spec:
  completions: 1
  ttlSecondsAfterFinished: 3600
  backoffLimit: 0
  template:
    metadata:
      name: add-domain
    spec:
      restartPolicy: Never
      containers:
      - name: init
        image: placeos/init:placeos-2.2509.2
        command: ["bash", "-c"]
        args:
        - |
          /app/bin/task create:authority domain=$PLACE_DOMAIN
        env:
          - name: PLACE_DOMAIN
            value: ""
        # These env vars are not required for the task but init requires they are set to run any task
          - name: PLACE_SKIP_PLACEHOLDERS
            value: "true"
          - name: PLACE_EMAIL
            value: "support@place.tech"
          - name: PLACE_USERNAME
            value: "support@place.tech"
          - name: PLACE_AUTH_HOST
            value: "auth:3000"
          - name: PLACE_TLS
            value: "true"
          - name: ENV
            valueFrom:
              configMapKeyRef:
                name: core
                key: ENV
        # These env vars are required to connect to postgres
        envFrom:
          - configMapRef:
              name: postgres-client
          - secretRef:
              name: postgres-client
          - secretRef:
              name: init