apiVersion: batch/v1
kind: Job
metadata:
  name: add-user
  namespace: placeos
spec:
  completions: 1
  ttlSecondsAfterFinished: 3600
  backoffLimit: 0
  template:
    metadata:
      name: add-user
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      restartPolicy: Never
      containers:
      - name: init
        image: placeos/init:placeos-2.2511.1
        securityContext:
          allowPrivilegeEscalation: false
        command: ["bash", "-c"]
        args: [ "/app/bin/task create:user authority_id='s0mek1nd4UUID' email='support@place.tech' username='burger' password='burgerR00lz' sys_admin=true support=true" ] #gitleaks:allow
        env:
        # These env vars are not required for the task but init requires they are set to run any task
          - name: PLACE_DOMAIN
            value: ""
          - name: PLACE_SKIP_PLACEHOLDERS
            value: "true"
          - name: PLACE_EMAIL
            value: "support@place.tech"
          - name: PLACE_USERNAME
            value: "support@place.tech"
          - name: PLACE_AUTH_HOST
            value: "auth:3000"
          - name: PLACE_TLS
            value: "true"
          - name: ENV
            valueFrom:
              configMapKeyRef:
                name: core
                key: ENV
        # These env vars are required to connect to postgres
        envFrom:
          - configMapRef:
              name: postgres-client
          - secretRef:
              name: postgres-client
          - secretRef:
              name: init
