apiVersion: batch/v1

kind: Job
metadata:
  name: run-init
spec:
  completions: 1
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      name: run-init
    spec:
      containers:
      - name: init
        image: placeos/init:placeos-2.2509.2
        imagePullPolicy: IfNotPresent
        env:
          # Set PLACE_SKIP_PLACEHOLDERS to false to create systems/zones/drivers examples
          - name: PLACE_SKIP_PLACEHOLDERS
            value: "true"
          # PLACE_DOMAIN can be set to create a domain (placeos authority)
          - name: PLACE_DOMAIN
            value: ""
          - name: PLACE_EMAIL
            value: "support@place.tech"
          - name: PLACE_USERNAME
            value: "support@place.tech"
          - name: PLACE_AUTH_HOST
            value: "auth:3000"
          - name: PLACE_TLS
            value: "true"
        envFrom:
        - secretRef:
            name: init
        - configMapRef:
            name: core
        - secretRef:
            name: postgres-client
        - configMapRef:
            name: postgres-client
      restartPolicy: Never
  backoffLimit: 0
