apiVersion: v2
name: placeos
description: An Umbrella Chart for PlaceOS and its dependencies

type: application
version: 2.0.0
appVersion: "2.2304.0"

dependencies:
# PlaceOS components
  - name: api
    version: 2.0.0
    condition: api.enabled

  - name: auth
    version: 2.0.0
    condition: auth.enabled

  - name: core
    version: 2.0.0
    condition: core.enabled

  - name: dispatch
    version: 2.0.0
    condition: dispatch.enabled

  - name: frontendloader
    version: 2.0.0
    condition: frontendloader.enabled

  - name: searchingest
    version: 2.0.0
    condition: searchingest.enabled

  - name: triggers
    version: 2.0.0
    condition: triggers.enabled

  - name: staff
    version: 2.0.0
    condition: staff.enabled

  - name: init
    version: 2.0.0
    condition: init.enabled

# Third party helm charts
  - name: etcd
    version: ~8.5.9
    #version: 3.5.4
    repository: https://charts.bitnami.com/bitnami
    condition: etcd.enabled
    # tags: # (optional)
    #   - Tags can be used to group charts for enabling/disabling together
    # alias: (optional) Alias to be used for the chart. Useful when you have to add the same chart multiple times

  - name: elasticsearch
    version: ~18.2.9
    repository: https://charts.bitnami.com/bitnami
    condition: elasticsearch.enabled
    # tags: # (optional)
    #   - Tags can be used to group charts for enabling/disabling together
    # alias: (optional) Alias to be used for the chart. Useful when you have to add the same chart multiple times

  - name: redis
    version: ~17.3.11
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
    # tags: # (optional)
    #   - Tags can be used to group charts for enabling/disabling together
    # alias: (optional) Alias to be used for the chart. Useful when you have to add the same chart multiple times

  - name: influxdb
    version: ~5.3.3
    repository: https://charts.bitnami.com/bitnami
    condition: influxdb.enabled
    # tags: # (optional)
    #   - Tags can be used to group charts for enabling/disabling together
    # alias: (optional) Alias to be used for the chart. Useful when you have to add the same chart multiple times

  - name: mosquitto
    version: ~0.2.0
    repository: https://halkeye.github.io/helm-charts/
    condition: mosquitto.enabled
    # tags: # (optional)
    #   - Tags can be used to group charts for enabling/disabling together
    # import-values: # (optional)
    #   - ImportValues holds the mapping of source values to parent key to be imported. Each item can be a string or pair of child/parent sublist items.
    # alias: (optional) Alias to be used for the chart. Useful when you have to add the same chart multiple times

  - name: postgresql-ha
    version: ~11.2.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    # tags: # (optional)
    #   - Tags can be used to group charts for enabling/disabling together
    alias: postgresql
