# Example override values for a local deployment

############################
##### PlaceOS Services #####
############################
frontendloader:
  httpSidecar: true

###########################################
##### Third Party Supporting Services #####
###########################################
etcd:
  enabled: true
elasticsearch:
  enabled: true
redis:
  enabled: true
postgresql:
  enabled: true
influxdb:
  enabled: true

global:
  placeDomain: localhost
  customRedirectPort: 8443
