# Example override values for an Openshift v4 deployment

############################
#### Shared Configuration ##
############################
xseccompProfileType: &seccompProfileType RuntimeDefault
xstorageClassName: &storageClassName default
xserviceAccountName: &serviceAccountName placeos-anyuid

############################
##### PlaceOS Services #####
############################
api:
  serviceAccountName: *serviceAccountName
  deployment:
    securityContext:
      runAsUser: null
      seccompProfile:
        type: *seccompProfileType
    podPriorityClassName: ""
auth:
  serviceAccountName: *serviceAccountName
  deployment:
    securityContext:
      runAsUser: null
      seccompProfile:
        type: *seccompProfileType
    podPriorityClassName: ""
core:
  serviceAccountName: *serviceAccountName
  deployment:
    securityContext:
      runAsUser: null
      seccompProfile:
        type: *seccompProfileType
    podPriorityClassName: ""
dispatch:
  serviceAccountName: *serviceAccountName
  deployment:
    securityContext:
      runAsUser: null
      seccompProfile:
        type: *seccompProfileType
    podPriorityClassName: ""
frontendloader:
  serviceAccountName: *serviceAccountName
  httpSidecar: true
  deployment:
    securityContext:
      runAsUser: null
      seccompProfile:
        type: *seccompProfileType
    podPriorityClassName: ""
  httpDeployment:
    securityContext:
      runAsUser: null
      seccompProfile:
        type: *seccompProfileType
    podPriorityClassName: ""
triggers:
  serviceAccountName: *serviceAccountName
  deployment:
    securityContext:
      runAsUser: null
      seccompProfile:
        type: *seccompProfileType
    podPriorityClassName: ""
staff:
  serviceAccountName: *serviceAccountName
  deployment:
    securityContext:
      runAsUser: null
      seccompProfile:
        type: *seccompProfileType
    podPriorityClassName: ""
source:
  serviceAccountName: *serviceAccountName
  deployment:
    securityContext:
      runAsUser: null
      seccompProfile:
        type: *seccompProfileType
    podPriorityClassName: ""
init:
  serviceAccountName: *serviceAccountName
  deployment:
    securityContext:
      runAsUser: null
      seccompProfile:
        type: *seccompProfileType
    podPriorityClassName: ""

###########################################
##### Third Party Supporting Services #####
###########################################
redis:
  enabled: true
  serviceAccount:
    create: false
    name: *serviceAccountName
  podSecurityContext:
    fsgroup: null
  containerSecurityContext:
    runAsUser: null
    runasGroup: null
    seccompProfile:
      type: *seccompProfileType
  master:
    persistence:
      enabled: true
      mountPath: /data
      subPath: ''
      storageClass: *storageClassName
      accessModes:
        - ReadWriteOnce
      size: 8Gi

postgresql:
  enabled: true
  serviceAccount:
    create: false
    name: *serviceAccountName
  podSecurityContext:
    seccompProfile:
      type: *seccompProfileType
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 256Mi

influxdb:
  enabled: true
  serviceAccount:
    create: false
  podSecurityContext:
    seccompProfile:
      type: *seccompProfileType
  influxdb:
    securityContext:
      enabled: false

global:
  placeDomain: ""
  openshift: true
