# Example override values for an Openshift v4 deployment

############################
##### PlaceOS Services #####
############################
frontendloader:
  httpSidecar: true

###########################################
##### Third Party Supporting Services #####
###########################################
etcd:
  enabled: true

elasticsearch:
  enabled: true
  # Sets vm.max_map_count on the host node
  # Not required on Openshift v4
  sysctlImage:
    enabled: false

rethinkdb:
  enabled: true
  rbac:
    # Specifies whether RBAC resources should be created
    # Disable for environments without permission to create RBAC or ServiceAccounts
    create: true
  serviceAccount:
    # Specifies whether a ServiceAccount should be created
    # Disable for environments without permission to create RBAC or ServiceAccounts
    create: true

redis:
  enabled: true

postgresql:
  enabled: true

global:
  placeDomain: ""
