# Example override values for an Openshift v4 deployment

############################
#### Shared Configuration ##
############################
xseccompProfileType: &seccompProfileType RuntimeDefault

############################
##### PlaceOS Services #####
############################
api:
  serviceAccountName: placeos-anyuid
  deployment:
    securityContext:
      seccompProfile:
        type: *seccompProfileType
    podPriorityClassName: ""
auth:
  serviceAccountName: placeos-anyuid
  deployment:
    securityContext:
      seccompProfile:
        type: *seccompProfileType
    podPriorityClassName: ""
core:
  serviceAccountName: placeos-anyuid
  deployment:
    securityContext:
      seccompProfile:
        type: *seccompProfileType
    podPriorityClassName: ""
dispatch:
  serviceAccountName: placeos-anyuid
  deployment:
    securityContext:
      seccompProfile:
        type: *seccompProfileType
    podPriorityClassName: ""
frontendloader:
  serviceAccountName: placeos-anyuid
  httpSidecar: true
  deployment:
    securityContext:
      seccompProfile:
        type: *seccompProfileType
    podPriorityClassName: ""
  httpDeployment:
    securityContext:
      seccompProfile:
        type: *seccompProfileType
    podPriorityClassName: ""
searchingest:
  serviceAccountName: placeos-anyuid
  deployment:
    securityContext:
      seccompProfile:
        type: *seccompProfileType
    podPriorityClassName: ""
triggers:
  serviceAccountName: placeos-anyuid
  deployment:
    securityContext:
      seccompProfile:
        type: *seccompProfileType
    podPriorityClassName: ""
staff:
  serviceAccountName: placeos-anyuid
  deployment:
    securityContext:
      seccompProfile:
        type: *seccompProfileType
    podPriorityClassName: ""
source:
  serviceAccountName: placeos-anyuid
  deployment:
    securityContext:
      seccompProfile:
        type: *seccompProfileType
    podPriorityClassName: ""
init:
  serviceAccountName: placeos-anyuid
  deployment:
    securityContext:
      seccompProfile:
        type: *seccompProfileType
    podPriorityClassName: ""

###########################################
##### Third Party Supporting Services #####
###########################################
elasticsearch:
  enabled: true
  # Sets vm.max_map_count on the host node
  # Not required on Openshift v4
  sysctlImage:
    enabled: false
  podSecurityContext:
    seccompProfile:
      type: *seccompProfileType
  master:
    replicas: 3
    serviceAccount:
      create: false
      name: placeos-anyuid
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 25m
        memory: 256Mi
    persistence:
      enabled: true
      storageClass: default
      accessModes:
        - ReadWriteOnce
      size: 8Gi
  coordinating:
    replicas: 0
    serviceAccount:
      create: false
      name: placeos-anyuid
    resources:
      limits:
        cpu: 100m
        memory: 384Mi
      requests:
        cpu: 25m
        memory: 256Mi
    securityContext:
      enabled: false
  data:
    replicas: 2
    serviceAccount:
      create: false
      name: placeos-anyuid
    resources:
      limits:
        cpu: 1
        memory: 2176Mi
      requests:
        cpu: 25m
        memory: 2048Mi
    persistence:
      enabled: true
      storageClass: default
      accessModes:
        - ReadWriteOnce
      size: 8Gi

redis:
  enabled: true
  serviceAccount:
    create: false
    name: placeos-anyuid
  podSecurityContext:
    seccompProfile:
      type: *seccompProfileType
  persistence:
    enabled: true
    mountPath: /data
    subPath: ''
    storageClass: default
    accessModes:
      - ReadWriteOnce
    size: 8Gi

postgresql:
  enabled: true
  serviceAccount:
    create: false
    name: placeos-anyuid
  podSecurityContext:
    seccompProfile:
      type: *seccompProfileType
  resources:
    limits:
      cpu: 4
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 256Mi

influxdb:
  enabled: true
  serviceAccount:
    create: false
  podSecurityContext:
    seccompProfile:
      type: *seccompProfileType
  influxdb:
    securityContext:
      enabled: false

global:
  placeDomain: ""
  openshift: true
