# Example with override values for a GCP placeos deployment.

############################
##### PlaceOS Services #####
############################
api:
  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx
      ingress.kubernetes.io/ssl-redirect: "true"

auth:
  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx
      ingress.kubernetes.io/ssl-redirect: "true"

dispatch:
  udpLoadbalancer:
    annotations:
      cloud.google.com/load-balancer-type: "Internal"
  tcpLoadbalancer:
    annotations:
      cloud.google.com/load-balancer-type: "Internal"

frontends:
  httpSidecar: false
  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx
      ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/app-root: "/backoffice/"

staff:
  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx
      ingress.kubernetes.io/ssl-redirect: "true"

###########################################
##### Third Party Supporting Services #####
###########################################
etcd:
  enabled: true
elasticsearch:
  enabled: true
rethinkdb:
  enabled: true
redis:
  enabled: true
postgres:
  enabled: false

global:
  placeDomain: ""
  gcpbackendConfig:
    enabled: false
    name: placeos-core
    config: {}
    global_static_ip_name: ""
    loadbalancerAccessType: ""
