# Example with override values for a Azure placeos deployment.

############################
##### PlaceOS Services #####
############################
api:
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      ingress.kubernetes.io/ssl-redirect: "true"

auth:
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      ingress.kubernetes.io/ssl-redirect: "true"

# https://docs.aws.amazon.com/eks/latest/userguide/load-balancing.html
dispatch:
  udpLoadbalancer:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  tcpLoadbalancer:
    annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"

frontendloader:
  httpSidecar: true
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/app-root: "/backoffice/"

###########################################
##### Third Party Supporting Services #####
###########################################
etcd:
  enabled: true
elasticsearch:
  enabled: true
rethinkdb:
  enabled: true
redis:
  enabled: true
postgresql:
  enabled: true
influxdb:
  enabled: true

global:
  placeDomain: ""
