---
# defaults file for placeos.networkpolicies

placeos_namespace: placeos
placeos_to_ns:
    # - rethinkdb
    # - elasticsearch
    # - redis
    # - influxdb
    # - mosquitto
internal_ns:
    # - rethinkdb
    # - elasticsearch
    # - redis
    - "{{ placeos_namespace }}"
    # - influxdb
    # - mosquitto
policy_state: "present"

ingress_upstream: "ingress-upstream"
ingress_namespace: "placeos"
ingress_application_name: "ingress-nginx"
ingress_deployment: "ingress-nginx-controller"
