---
# defaults file for placeos.networkpolicies

placeos_namespace: placeos
placeos_to_ns:
    - etcd
    - rethinkdb
    - elasticsearch
    - redis
    - influxdb
    - mosquitto
internal_ns:
    - etcd
    - rethinkdb
    - elasticsearch
    - redis
    - influxdb
    - mosquitto
    - "{{ placeos_namespace }}"
policy_state: "present"

ingress_upstream: "ingress-upstream"
ingress_namespace: "ingress-nginx"
ingress_application_name: "ingress-nginx"