apiVersion: v2
name: auth
description: A PlaceOS helm chart for the Auth component

type: application

version: 2.0.0

# This number is reflected in the container version deployed
appVersion: placeos-2.2304.0

