{
 "title": "Core Error Breakdown",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Core Errors / Min",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"core\", level=\"ERROR\"} [1m]))",
     "maxLines": 10
    }
   ]
  },
  {
   "title": "Core Errors",
   "type": "logs",
   "gridPos": { "h": 24, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "{app=\"core\", namespace=\"placeos\", level=\"ERROR\"}",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "`program` error count",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (program) (\r\n  count_over_time({app=\"core\", level=\"ERROR\"} \r\n  | pattern `<_> program=<program> <_>` [1m])\r\n)"
    }
   ]
  },
  {
   "title": "`source` error count",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (source) (\r\n  count_over_time({app=\"core\", level=\"ERROR\"} \r\n  | pattern `<_> source=<source> <_>` [1m])\r\n)"
    }
   ]
  },
  { "title": "Driver Running Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Error Launching Driver Errors / Min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"placeos\", app=\"core\", level=\"ERROR\"} |= `error launching driver` [1m]))",
     "maxLines": 10
    }
   ]
  },
  {
   "title": "Driver Lauch Timout Errors / Min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"placeos\", app=\"core\", level=\"ERROR\"} |= `driver launch timeout` [1m]))",
     "maxLines": 10
    }
   ]
  },
  {
   "title": "Failed To Obtain Running Modules Errors / Min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"placeos\", app=\"core\", level=\"ERROR\"} |= `failed to obtain running modules on driver` [1m]))",
     "maxLines": 10
    }
   ]
  },
  {
   "title": "Error Launching Driver Errors",
   "type": "logs",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{app=\"core\", level=\"ERROR\", namespace=\"placeos\"} |= `error launching driver`",
     "maxLines": 10
    }
   ]
  },
  {
   "title": "Driver Lauch Timout Errors",
   "type": "logs",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "targets": [
    {
     "expr": "{app=\"core\", level=\"ERROR\", namespace=\"placeos\"} |= `driver launch timeout`",
     "maxLines": 10
    }
   ]
  },
  {
   "title": "Failed To Obtain Running Modules Errors",
   "type": "logs",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "targets": [
    {
     "expr": "{app=\"core\", level=\"ERROR\", namespace=\"placeos\"} |= `failed to obtain running modules on driver`",
     "maxLines": 10
    }
   ]
  }
 ]
}