{
 "title": "PlaceOS Logs",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{app=\"api\", namespace=\"placeos\"} |= ``",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "Auth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Auth",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "{app=\"auth\", namespace=\"placeos\"} |= ``",
       "maxLines": 100
      }
     ]
    }
   ]
  },
  {
   "title": "Core",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Core",
     "type": "logs",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "{app=\"core\", namespace=\"placeos\"} |= ``",
       "maxLines": 100
      }
     ]
    }
   ]
  },
  {
   "title": "Frontend Loader",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Frontend Loader",
     "type": "logs",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "{app=\"frontend-loader\", namespace=\"placeos\"} |= ``",
       "maxLines": 100
      }
     ]
    }
   ]
  },
  {
   "title": "Triggers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Triggers",
     "type": "logs",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "{app=\"triggers\", namespace=\"placeos\"} |= ``",
       "maxLines": 100
      }
     ]
    }
   ]
  },
  {
   "title": "Staff",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Staff",
     "type": "logs",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "{app=\"staff\", namespace=\"placeos\"} |= ``",
       "maxLines": 100
      }
     ]
    }
   ]
  },
  {
   "title": "Source",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Source",
     "type": "logs",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "{app=\"source\", namespace=\"placeos\"} |= ``",
       "maxLines": 100
      }
     ]
    }
   ]
  }
 ]
}