{
 "title": "PlaceOS Service Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Response Times (ms)",
   "type": "timeseries",
   "description": "1 minute average",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg by(container) (\r\n  avg_over_time({app=\"api\"} | json | unwrap duration [1m])\r\n)"
    }
   ]
  },
  {
   "title": "Core Response Times (ms)",
   "type": "timeseries",
   "description": "1 minute average",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "avg by(container) (\r\n  avg_over_time({app=\"core\"} | json | unwrap duration [1m])\r\n)"
    }
   ]
  },
  {
   "title": "Staff Response Times (ms)",
   "type": "timeseries",
   "description": "1 minute average",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "avg by(container) (\r\n  avg_over_time({app=\"staff\"} | json | unwrap duration [1m])\r\n)"
    }
   ]
  },
  {
   "title": "API Requests / Min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({app=\"api\"} |= `status` | logfmt [$__auto]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Core Requests / Min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({app=\"core\"} |= `status` | logfmt [$__auto]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Staff Requests / Min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({app=\"staff\"} |= `status` | logfmt [$__auto]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  { "title": "Driver Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Module Execs / Min",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"core\"} |= `/execute` | json | __error__!=\"JSONParserErr\" [1m])) by (path)"
    }
   ]
  },
  {
   "title": "Module Exec Response Times Avg (ms)",
   "type": "timeseries",
   "description": "1 minute average",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "avg_over_time({app=\"core\"} |= `execute` | json | __error__!=\"JSONParserErr\" | unwrap duration [1m]) by (path)\r\n"
    }
   ]
  },
  {
   "title": "Module Exec Response Times Max (ms)",
   "type": "timeseries",
   "description": "1 minute average",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "max_over_time({app=\"core\"} |= `execute` | json | __error__!=\"JSONParserErr\" | unwrap duration [1m]) by (path)\r\n"
    }
   ]
  },
  { "title": "Application Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "API Errors / Min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"api\", level=\"ERROR\"} [1m]))",
     "maxLines": 10
    }
   ]
  },
  {
   "title": "Core Errors / Min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 48 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"placeos\", app=\"core\", level=\"ERROR\"} [1m]))",
     "maxLines": 10
    }
   ]
  },
  {
   "title": "Driver Errors / Min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"core\"} |= `level=[E]` |= `driver` [1m]))",
     "maxLines": 10
    }
   ]
  },
  {
   "title": "Staff Errors / Min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 48 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"staff\"} |= `Error` [1m]))",
     "maxLines": 10
    }
   ]
  },
  {
   "title": "API Errors",
   "type": "logs",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "{app=\"api\", level=\"ERROR\"}",
     "maxLines": 10
    }
   ]
  },
  {
   "title": "Core Errors",
   "type": "logs",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 55 },
   "targets": [
    {
     "expr": "{app=\"core\", level=\"ERROR\", namespace=\"placeos\"}",
     "maxLines": 10
    }
   ]
  },
  {
   "title": "Driver Errors",
   "type": "logs",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "{app=\"core\"} |= `level=[E]` |= `program=driver`",
     "maxLines": 10
    }
   ]
  },
  {
   "title": "Staff Errors",
   "type": "logs",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 55 },
   "targets": [
    {
     "expr": "{app=\"staff\"} |= `Error`",
     "maxLines": 10
    }
   ]
  },
  { "title": "Request Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "API 5** Requests / Min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"api\"} |= `\"status\":5` [1m]))"
    }
   ]
  },
  {
   "title": "Core 5** Requests / Min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 63 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"core\"} |= `\"status\":5` [1m]))"
    }
   ]
  },
  {
   "title": "Staff 5** Requests / Min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 63 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"staff\"} |= `status: 5` [1m]))"
    }
   ]
  },
  {
   "title": "API 5** Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "{app=\"api\"} |= `\"status\":5`",
     "maxLines": 10
    }
   ]
  },
  {
   "title": "Core 5** Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 70 },
   "targets": [
    {
     "expr": "{app=\"core\"} |= `\"status\":5`",
     "maxLines": 10
    }
   ]
  },
  {
   "title": "Staff 5** Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 70 },
   "targets": [
    {
     "expr": "{app=\"staff\"} |= `status: 5`",
     "maxLines": 10
    }
   ]
  }
 ]
}