{
 "title": "PlaceOS Pod Resources",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container",
    "query": {
     "query": "label_values(kube_pod_container_status_running{namespace=\"placeos\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Namespace / Cluster Memory Use",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container=~\".*\",namespace=\"placeos\",container=\"\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\".*\"}) * 100"
    }
   ]
  },
  {
   "title": "Namespace / Cluster CPU Use",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{pod=~\".*\", namespace=\"placeos\",container=\"\"}[1m])) * 100) / sum(machine_cpu_cores{kubernetes_io_hostname=~\".*\"})"
    }
   ]
  },
  {
   "title": "Namespace Volume Use",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{namespace=\"placeos\"})\r\n/\r\nsum(kubelet_volume_stats_capacity_bytes{namespace=\"placeos\"}) \r\n* 100\r\n"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\".*\", namespace=\"placeos\",container=\"\"})"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"placeos\", pod=~\".*\", resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Limts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"placeos\", pod=~\".*\", resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Cluster Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_memory_bytes{kubernetes_io_hostname=~\".*\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=~\".*\",namespace=\"placeos\",container=\"\"}[1m]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"placeos\", pod=~\".*\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Limits",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"placeos\", pod=~\".*\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Cluster Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\".*\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{namespace=\"placeos\"})\r\n\r\n"
    }
   ]
  },
  {
   "title": "Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\r\nsum(kubelet_volume_stats_capacity_bytes{namespace=\"placeos\"})"
    }
   ]
  },
  { "title": "Usage Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Pod Memory Use",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\".*\",namespace=\"placeos\",container=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Pod CPU Use",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\".*\",namespace=\"placeos\",container=\"\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Volume Use",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{namespace=\"placeos\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Memory Use",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\".*\",namespace=\"placeos\",container=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU Use",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\".*\",namespace=\"placeos\",container=\"\"}[1m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Volume Use %",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(kubelet_volume_stats_used_bytes{namespace=\"placeos\"}) by (persistentvolumeclaim)\r\n  /\r\nsum(kubelet_volume_stats_capacity_bytes{namespace=\"placeos\"}) by (persistentvolumeclaim)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Memory Limit %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(container_memory_working_set_bytes{pod=~\".*\",namespace=\"placeos\",container=\"\"}) by (pod)\r\n/\r\nsum(kube_pod_container_resource_limits{pod=~\".*\",namespace=\"placeos\",resource=\"memory\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU Request %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(rate(container_cpu_usage_seconds_total{pod=~\".*\",namespace=\"placeos\",container=\"\"}[1m])) by (pod)\r\n/\r\nsum(kube_pod_container_resource_requests{pod=~\".*\",namespace=\"placeos\",resource=\"cpu\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Volume Use %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "100 * sum(kubelet_volume_stats_used_bytes{namespace=\"placeos\"}) by (persistentvolumeclaim)\r\n  /\r\nsum(kubelet_volume_stats_capacity_bytes{namespace=\"placeos\"}) by (persistentvolumeclaim)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Container OOM Kill",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by(container) ((kube_pod_container_status_restarts_total - kube_pod_container_status_restarts_total offset 10m >= 1) and ignoring (reason) min_over_time(kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\"}[10m]) == 1)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Container CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=\"placeos\"}[1m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Ready Status",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{namespace=\"placeos\", condition=\"true\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum by(container) (kube_pod_container_status_restarts_total - kube_pod_container_status_restarts_total offset 10m >= 1)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Pods network I/O (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum (rate(container_network_receive_bytes_total{image!=\"\",name=~\"^.*\",namespace=\"placeos\"}[1m])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "-sum (rate(container_network_transmit_bytes_total{image!=\"\",name=~\"^.*\",namespace=\"placeos\"}[1m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "$container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 }, "repeat": "container" },
  {
   "title": "Ready Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"placeos\", container=\"$container\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Memory Use",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 2, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\".*\",namespace=\"placeos\",container=\"$container\"}) by (pod)",
     "legendFormat": "Used"
    },
    {
     "expr": "kube_pod_container_resource_requests{pod=~\".*\",namespace=\"placeos\",container=\"$container\",resource=\"memory\"}",
     "legendFormat": "Request"
    },
    {
     "expr": "kube_pod_container_resource_limits{pod=~\".*\",namespace=\"placeos\",container=\"$container\",resource=\"memory\"}",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Container CPU Use",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 8, "y": 54 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$container.*\",namespace=\"placeos\",container=\"\"}[1m])) by (pod)",
     "legendFormat": "Used"
    },
    {
     "expr": "kube_pod_container_resource_requests{pod=~\".*\",namespace=\"placeos\",container=\"$container\",resource=\"cpu\"}",
     "legendFormat": "Request"
    },
    {
     "expr": "kube_pod_container_resource_limits{pod=~\".*\",namespace=\"placeos\",container=\"$container\",resource=\"cpu\"}",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Pods network I/O (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate(container_network_receive_bytes_total{image!=\"\",name=~\"^.*\",namespace=\"placeos\",pod=~\".*$container.*\"}[1m])) by (container)",
     "legendFormat": "↓ {{ pod_name }}"
    },
    {
     "expr": "- sum (rate(container_network_transmit_bytes_total{image!=\"\",name=~\"^.*\",namespace=\"placeos\",pod=~\".*$container.*\"}[1m])) by (container)",
     "legendFormat": "↑ {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Non-Ready Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_ready{namespace=\"placeos\", container=\"$container\"} == 0) or on() vector(0) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}