# Default values for dispatch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# deployment configuration for the dispatch pod
deployment:
  replicaCount: 1

  image:
    repository: placeos/dispatch
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    # tag: ""

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}

  # podSecurityContext for the pod
  podSecurityContext:
    fsGroup: 10001

  # securityContext for the container
  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    #runAsUser is defined at container build time and in most circumstances should not be changed
    runAsUser: 10001
  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

# autoscaling configuration for pod
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# secrets for the deployment exposed as environment variables to the pod
secrets:
  SERVER_SECRET: null

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# service exposed by deployment
service:
  type: ClusterIP
  port: 3000

udpLoadbalancer:
  type: LoadBalancer
  annotations: {}
  portMappings:
    - 161: 10161
    - 162: 10162

tcpLoadbalancer:
  type: LoadBalancer
  annotations: {}
  portMappings:
    - 23: 10023
  udpLoadbalancer:
