name: CI

on:
  push:

jobs:
  chart-directories:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kanga333/json-array-builder@main
        id: array
        with:
          cmd: find charts/placeos/charts -mindepth 1 -type d -not -name tests -not -name templates
    outputs:
      directories: ${{ steps.array.outputs.build }}

  kube-score-ckeck:
    needs: chart-directories
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        directory: ${{ fromJson(needs.chart-directories.outputs.directories) }}
    name: kube-score (Linux)

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: kube-score action step
        uses: piraces/kube-score-ga@v0.1.2
        id: ksga
        with:
          manifests-folders: '${{ matrix.directory }}/*.yaml'
          ignore-exit-code: 'false'
          kube-score-version: '1.11.0'
          output-file: 'output.txt'

      - name: Google Chat Notification
        if: failure()
        uses: Co-qn/google-chat-notification@releases/v1
        with:
            name: kube-score-ckeck
            url: ${{ secrets.PLACE_OS_CHAT_STDERR }}
            status: ${{ steps.ksga.outcome }}
