name: CI

on:
  push:

jobs:

  kube-lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Remove third-party dependencies from Chart.yaml
        run: |
          # Delete everything below the third party charts line in Chart.yaml
          awk '/# Third party helm charts/ { exit } { print }' charts/placeos/Chart.yaml > charts/placeos/Chart.yaml.tmp
          mv charts/placeos/Chart.yaml.tmp charts/placeos/Chart.yaml
      
      - name: Set Up Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: v3.18.2

      - name: Template Helm Charts
        run: |
          mkdir -p rendered-templates/${{ matrix.directory }}
          helm template lint-release ./charts/placeos -f ./charts/placeos/values.yaml --set global.placeDomain="test.domain" --skip-tests > rendered-templates/rendered.yaml

      # This prepares directory where github/codeql-action/upload-sarif@v1 looks up report files by default.
      - name: Create ../results directory for SARIF report files
        shell: bash
        run: mkdir -p ../results

      - name: Scan yaml files with kube-linter
        continue-on-error: true 
        uses: stackrox/kube-linter-action@v1.0.6
        id: kube-linter-action-scan
        with:
          directory: rendered-templates
          format: sarif
          output-file: ../results/kube-linter.sarif

      - name: Upload SARIF report files to GitHub
        uses: github/codeql-action/upload-sarif@v3

      # Ensure the workflow eventually fails if files did not pass kube-linter checks.
      - name: Verify kube-linter-action succeeded
        shell: bash
        run: |
          echo "If this step fails, kube-linter found issues. Check the output of the scan step above."
          [[ "${{ steps.kube-linter-action-scan.outcome }}" == "success" ]]
