name: CI

on:
  push:

jobs:
  chart-directories:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kanga333/json-array-builder@main
        id: array
        with:
          cmd: find charts/placeos/charts -mindepth 1 -type d -not -name tests -not -name templates
    outputs:
      directories: ${{ steps.array.outputs.build }}

  kube-lint:
    needs: chart-directories
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        directory: ${{ fromJson(needs.chart-directories.outputs.directories) }}
    steps:
      - uses: actions/checkout@v2

      - name: Scan yaml files with kube-linter
        continue-on-error: true 
        uses: stackrox/kube-linter-action@v1.0.4
        id: kube-linter-action-scan
        with:
          directory: ${{ matrix.directory }}
          format: sarif
          output-file: kube-linter.sarif

      - name: Upload SARIF report files to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: ${{ matrix.directory }}/kube-linter.sarif

      # Ensure the workflow eventually fails if files did not pass kube-linter checks.
      - name: Verify kube-linter-action succeeded
        shell: bash
        run: |
          echo "If this step fails, kube-linter found issues. Check the output of the scan step above."
          [[ "${{ steps.kube-linter-action-scan.outcome }}" == "success" ]]

  kube-score-ckeck:
    needs: chart-directories
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        directory: ${{ fromJson(needs.chart-directories.outputs.directories) }}
    name: kube-score (Linux)

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: kube-score action step
        uses: piraces/kube-score-ga@v0.1.2
        id: ksga
        with:
          manifests-folders: '${{ matrix.directory }}/*.yaml'
          ignore-exit-code: 'false'
          kube-score-version: '1.11.0'
          output-file: 'output.txt'

      - name: Google Chat Notification
        uses: Co-qn/google-chat-notification@releases/v1
        with:
            name: kube-score-ckeck
            url: ${{ secrets.PLACE_OS_CHAT_STDOUT }}
            status: ${{ steps.ksga.outcome }}
        if: failure()
